In [2]:
import numpy as np

In [3]:
# You can do calculations on 2 arrays -
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
print(a * b)

[ 2  9 20]


In [4]:
# 2D array
c = np.array([[1, 2, 3], [3, 2, 1]])

# To get the dimensions of an array
print(c.ndim)

# To see the shape - 
print(c.shape)

2
(2, 3)


In [5]:
# To see the data type of the array
print(c.dtype)

int64


In [6]:
# To specify dtype - 
d = np.array([1, 2], dtype='int16')
print(d.dtype)
print(d.itemsize)

int16
2


In [7]:
# To access/change specific elements/rows/columns

e = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# Get a specific element
print(e[1, 3]) # 2nd row, 4th column

# Get a specific row
print(e[0,:]) # 1st row

# Get a specific column
print(e[:, 1]) # 2nd Column

# Get alternate numbers starting from 2nd element of 1st row
print(e[0, 0:-1:2])

# To change an element
e[1, 3] = 20
print(e)

# To change a column
e[:, 2] = [30, 30]
print(e)

# To change a row - make all of them 10
e[0, :] = 10 
# If its the same value across all columnns, 
# you can specify the value just once instead of a list
print(e)

9
[1 2 3 4 5]
[2 7]
[1 3]
[[ 1  2  3  4  5]
 [ 6  7  8 20 10]]
[[ 1  2 30  4  5]
 [ 6  7 30 20 10]]
[[10 10 10 10 10]
 [ 6  7 30 20 10]]


In [12]:
# Arrays with just 0s or 1s
zero = np.zeros((5, 5))
print(zero)
# Specify dtype='int32' to remove float
one = np.ones(5, dtype='int32')
print(one)

# Any other number
fours = np.full((2, 3), 4)
print(fours)

# Reuse the shape on an existing array, but with all 5s
f = np.full_like(e, 5)
print(f)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1 1 1 1 1]
[[4 4 4]
 [4 4 4]]
[[5 5 5 5 5]
 [5 5 5 5 5]]
[[0.07646891 0.8240437  0.52729575]
 [0.66538833 0.89854334 0.71457015]
 [0.4356604  0.46925031 0.68287286]]
[6 0 6 7 5]
[[3 9 1]
 [5 8 0]
 [3 9 5]]


In [18]:
# Random numbers
rnd1 = np.random.rand(3, 3)
# Using random integers between limits 0 and 10
rnd2 = np.random.randint(0,10, 5)
# 2D array with random integers
rnd3 = np.random.randint(0,10,(3,3))
print(rnd1)
print(rnd2)
print(rnd3)

# Generate same random number multiple times
np.random.seed(101)
rnd4 = np.random.randint(0,100,10)
print(rnd4)

# Linearly spaced array
# 6 linearly spaced elements between 0 and 10
lnr1 = np.linspace(0,10,6)
# 21 linearly spaced elements between 0 and 10
lnr2 = np.linspace(0,10,21)
print(lnr1)
print(lnr2)

[[0.30696622 0.89361308 0.72154386]
 [0.18993895 0.55422759 0.35213195]
 [0.1818924  0.78560176 0.96548322]]
[3 2 8 9 3]
[[7 0 9]
 [7 9 8]
 [4 3 3]]
[95 11 81 70 63 87 75  9 77 40]
[ 0.  2.  4.  6.  8. 10.]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [9]:
# List vs Array
my_list = [0,1,2,3,4]
arr = np.array(my_list)
print(my_list)
print(arr)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [11]:
# Arrange
# arange integers, takes in start,stop, and step size
arr1 = np.arange(0,10)
brr2 = np.arange(0,10,2)
print(arr1)
print(brr2)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [20]:
# Max, min, mean and index
a = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
print(f"Max = {a.max()}, Min = {a.min()}, Mean = {a.mean()}")
# To get the index location of max and mean
print(f"Max value is at {a.argmax()} and Min value is at {a.argmin()}")

Max = 29, Min = 2, Mean = 12.9
Max value is at 9 and Min value is at 0
